insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '이것이 자바다', '한빛미디어', '김경식');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '오라클 SQL과 PL/SQL', '생능출판사', '서진수');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, 'JSP 웹 프로그래밍 기초', '가메출판사', '최범균');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '요구사항 확인 모듈', '한국출판사', '김진수');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, 'UI구현 및 테스트 모듈', '숲출판사', '박진남');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '30일! 애플리케이션 구현', '숲출판사', '이진호');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal,  '파이썬의 정석', '도우출판사', '남궁성');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '지능형 웹 알고리즘', '위키북스', '김광일');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '30일! 애플리케이션 테스트', '숲출판사', '박진남');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '이기적인 스프링', '영진닷컴', '박영남');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '이기적인 UML', '영진닷컴', '박영남');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '안드로이드 생존코딩', '한빛미디어', '오준석');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '30일! 텍스트마이닝', '숲출판사', '반윤정');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '데스크탑 UI/UX 설계', '한빛미디어', '오준석');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '나도 반응형웹 분석가', '가을북스', '김시연');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '빅테이터의 정석', '도우출판사', '남궁성');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '웹서버의 정석', '도우출판사', '김진아');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '시스템의 정석 기초편', '도우출판사', '김진아');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '나도 백엔드 개발자 될래요', '가능출판사', '김서연');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '나도 프레임워크 개발자 될래요', '가능출판사', '김서연');
insert into tblBook(seqBook, name, publisher, writer) values (seqBook.nextVal, '나도 제이쿼리 마스터', '나무출판사', '김하연');