
--시험기초정보 더미
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,20,'트랜잭션의 특성을 나열해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,27,'다음 릴레이션의 Degree와 Cardinality는?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'IEEE 802.4의 표준안 내용으로 맞는 것은?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,29,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'다음 릴레이션의 Degree와 Cardinality는?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,28,'다음 릴레이션의 Degree와 Cardinality는?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,18,'IEEE 802.4의 표준안 내용으로 맞는 것은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,14,'다음 릴레이션의 Degree와 Cardinality는?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,25,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,27,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,19,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,26,'트랜잭션의 특성을 나열해라',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,22,'트랜잭션의 특성을 나열해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'트랜잭션의 특성을 나열해라',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,30,'트랜잭션의 특성을 나열해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'다음 릴레이션의 Degree와 Cardinality는?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,20,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,26,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,14,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,15,'한 번에 4개의 비트를 전송하려고 할 때 사용할 수 있는 디지털 변조 방식은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,20,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,27,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,12,'트랜잭션의 특성을 나열해라',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,30,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'다음 릴레이션의 Degree와 Cardinality는?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,19,'IEEE 802.4의 표준안 내용으로 맞는 것은?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,19,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,24,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'트랜잭션의 특성을 나열해라',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,11,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,14,'다음 릴레이션의 Degree와 Cardinality는?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,23,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,22,'IEEE 802.4의 표준안 내용으로 맞는 것은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,18,'IEEE 802.4의 표준안 내용으로 맞는 것은?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,14,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,29,'트랜잭션의 특성을 나열해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,12,'다음 릴레이션의 Degree와 Cardinality는?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,21,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,12,'다음 릴레이션의 Degree와 Cardinality는?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,22,'다음 릴레이션의 Degree와 Cardinality는?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,27,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,28,'트랜잭션의 특성을 나열해라',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'트랜잭션의 특성을 나열해라',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,12,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,22,'한 번에 4개의 비트를 전송하려고 할 때 사용할 수 있는 디지털 변조 방식은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,26,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,24,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,12,'한 번에 4개의 비트를 전송하려고 할 때 사용할 수 있는 디지털 변조 방식은?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,15,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,21,'다음 릴레이션의 Degree와 Cardinality는?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,20,'트랜잭션의 특성을 나열해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'다음 릴레이션의 Degree와 Cardinality는?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,29,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'트랜잭션의 특성을 나열해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,30,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,30,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,14,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,25,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,21,'트랜잭션의 특성을 나열해라',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,12,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,20,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,14,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,20,'다음 릴레이션의 Degree와 Cardinality는?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,28,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,16,'트랜잭션의 특성을 나열해라',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,22,'트랜잭션의 특성을 나열해라',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,16,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,28,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,24,'트랜잭션의 특성을 나열해라',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,30,'IEEE 802.4의 표준안 내용으로 맞는 것은?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'다음 릴레이션의 Degree와 Cardinality는?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,21,'트랜잭션의 특성을 나열해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,21,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,14,'트랜잭션의 특성을 나열해라',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,12,'한 번에 4개의 비트를 전송하려고 할 때 사용할 수 있는 디지털 변조 방식은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,28,'IEEE 802.4의 표준안 내용으로 맞는 것은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,23,'트랜잭션의 특성을 나열해라',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,30,'IEEE 802.4의 표준안 내용으로 맞는 것은?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,30,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'트랜잭션의 특성을 나열해라',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,29,'한 번에 4개의 비트를 전송하려고 할 때 사용할 수 있는 디지털 변조 방식은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,18,'다음 릴레이션의 Degree와 Cardinality는?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'한 번에 4개의 비트를 전송하려고 할 때 사용할 수 있는 디지털 변조 방식은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,20,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,15,'다음 릴레이션의 Degree와 Cardinality는?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,22,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,28,'트랜잭션의 특성을 나열해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,22,'다음 릴레이션의 Degree와 Cardinality는?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,19,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,11,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'다음 릴레이션의 Degree와 Cardinality는?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,23,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,24,'IEEE 802.4의 표준안 내용으로 맞는 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'트랜잭션의 특성을 나열해라',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,18,'다음 릴레이션의 Degree와 Cardinality는?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,19,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,21,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,12,'IEEE 802.4의 표준안 내용으로 맞는 것은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,24,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,11,'다음 릴레이션의 Degree와 Cardinality는?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,11,'다음 릴레이션의 Degree와 Cardinality는?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,30,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,30,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,18,'IEEE 802.4의 표준안 내용으로 맞는 것은?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,18,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,28,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'IEEE 802.4의 표준안 내용으로 맞는 것은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,26,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,19,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'트랜잭션의 특성을 나열해라',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,19,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,18,'트랜잭션의 특성을 나열해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,19,'IEEE 802.4의 표준안 내용으로 맞는 것은?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'다음 릴레이션의 Degree와 Cardinality는?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,24,'트랜잭션의 특성을 나열해라',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,26,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,16,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,29,'다음 릴레이션의 Degree와 Cardinality는?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,20,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,22,'다음 릴레이션의 Degree와 Cardinality는?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,20,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,16,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'다음 릴레이션의 Degree와 Cardinality는?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,24,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,23,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,11,'트랜잭션의 특성을 나열해라',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,15,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,28,'한 번에 4개의 비트를 전송하려고 할 때 사용할 수 있는 디지털 변조 방식은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,22,'다음 릴레이션의 Degree와 Cardinality는?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,25,'트랜잭션의 특성을 나열해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,28,'한 번에 4개의 비트를 전송하려고 할 때 사용할 수 있는 디지털 변조 방식은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,20,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,25,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,15,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,18,'트랜잭션의 특성을 나열해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,15,'IEEE 802.4의 표준안 내용으로 맞는 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,12,'트랜잭션의 특성을 나열해라',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,30,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,15,'트랜잭션의 특성을 나열해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,19,'트랜잭션의 특성을 나열해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,18,'한 번에 4개의 비트를 전송하려고 할 때 사용할 수 있는 디지털 변조 방식은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'한 번에 4개의 비트를 전송하려고 할 때 사용할 수 있는 디지털 변조 방식은?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,29,'다음 릴레이션의 Degree와 Cardinality는?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,25,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,30,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,15,'트랜잭션의 특성을 나열해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,15,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,14,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'한 번에 4개의 비트를 전송하려고 할 때 사용할 수 있는 디지털 변조 방식은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,20,'트랜잭션의 특성을 나열해라',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,26,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,24,'한 번에 4개의 비트를 전송하려고 할 때 사용할 수 있는 디지털 변조 방식은?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,28,'다음 릴레이션의 Degree와 Cardinality는?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,18,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,25,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,29,'다음 릴레이션의 Degree와 Cardinality는?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,11,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,19,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,16,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,20,'트랜잭션의 특성을 나열해라',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,11,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,16,'IEEE 802.4의 표준안 내용으로 맞는 것은?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,15,'다음 릴레이션의 Degree와 Cardinality는?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,26,'트랜잭션의 특성을 나열해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,21,'IEEE 802.4의 표준안 내용으로 맞는 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,24,'IEEE 802.4의 표준안 내용으로 맞는 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,23,'다음 릴레이션의 Degree와 Cardinality는?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,23,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'IEEE 802.4의 표준안 내용으로 맞는 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,19,'트랜잭션의 특성을 나열해라',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,11,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'트랜잭션의 특성을 나열해라',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,12,'트랜잭션의 특성을 나열해라',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,29,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,14,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,16,'IEEE 802.4의 표준안 내용으로 맞는 것은?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,29,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,22,'IEEE 802.4의 표준안 내용으로 맞는 것은?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,14,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,14,'IEEE 802.4의 표준안 내용으로 맞는 것은?',2)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,28,'데이터베이스에서 널(NULL) 값에 대한 설명으로 옳지 않은 것은?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'트랜잭션의 특성을 나열해라',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,13,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',3)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,22,'다음의 관계 대수식을 SQL 질의로 옳게 표현 한 것은?',5)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,18,'블랙박스 테스트 기법에 해당하는 내용을 모두 고르면?',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,17,'IEEE 802.4의 표준안 내용으로 맞는 것은?',4)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,29,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',1)
insert into tblBasicTest (seqBasicTest,seqOpenSubject,question,questionNum) values (seqBasicTest.nextVal,29,'DROP TABLE 인사 CASCADE SQL문의 실행결과를 설명해라',3)

